Feature/wazon 11
malinkamedok/wazon pull request #5
Opened 2024-04-15 17:14 UTC by ZDmEv

Добавил скелет сервиса accountservice.
Реализованы ручки:
*Get /user/{id} - для тестирования, получение информации о пользователе
*Get /healthCheck - хелсчек
*Get /getAllProducts - прокинута интеграция с сервисом storefront для получения всех продуктов
*Post"/product - тестовая ручка для тестирования метода репозитория InsertOrUpdateProduct()

2024-04-15 18:11 UTC, zhukoff-pavel requested changes

2024-04-15 18:11 UTC, zhukoff-pavel commented on migrations/init.sql
> +                           orderID SERIAL PRIMARY KEY,
Давай тут сделаем `orderID` также UUID? Кажется, имеет смысл держать единые ID по всей системе для межмодульных сущностей

2024-04-15 18:11 UTC, zhukoff-pavel commented on migrations/init.sql
> +                              userID SERIAL PRIMARY KEY,
Аналогично про UUID.
ID, получаемый перечислением -- не очень хорошая идея. 

В Auth-модуле можно будет держать пару tgid-uuid, а uuid использовать в качестве внутрисистемного идентификатора пользователя

2024-04-15 18:11 UTC, zhukoff-pavel commented on migrations/init.sql
> +    id uuid not null default public.uuid_generate_v4(),
Тут куда-то `unique` пропал...
Заодно можно сделать PRIMARY_KEY, коль уж такая пляска

2024-04-15 18:11 UTC, zhukoff-pavel commented on accountservice/internal/usecase/repo/postgres.go
> +func (p PostgresRepo) GetAllProducts(ctx context.Context, userId int64) ([]entity.Product, error) {
А что эта ручка делает? По коду похоже на вывод всех товаров, которые юзер когда-либо заказывал

2024-04-16 05:43 UTC, ZDmEv commented on migrations/init.sql
> +                           orderID SERIAL PRIMARY KEY,
Сделал id везде uuid

2024-04-16 05:52 UTC, ZDmEv commented on migrations/init.sql
> +    id uuid not null default public.uuid_generate_v4(),
Заменил везде not null + unique -> PRIMARY_KEY

2024-04-16 05:53 UTC, ZDmEv commented on accountservice/internal/usecase/repo/postgres.go
> +func (p PostgresRepo) GetAllProducts(ctx context.Context, userId int64) ([]entity.Product, error) {
Исправил нейминг метода, я его не успел вчера дописать. Этот метод достает из бд все товары в корзине пользователя по id пользователя.
Добавил ендпоинт /cart/user/{id}

2024-04-16 08:05 UTC, zhukoff-pavel approved these changes

2024-04-16 08:06 UTC, zhukoff-pavel commented
LGTM, еще ждем @malinkamedok с более опытным взглядом гофера)

2024-04-16 10:36 UTC, malinkamedok requested changes

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +	fmt.Printf("Получен id = %s", idStr)
почему не лог?

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +	fmt.Printf("Получен id = %s", idStr)
и, раз на то пошло, почему без \n?

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +func (routes *accountServiceRoutes) GetUserById(writer http.ResponseWriter, request *http.Request) {
принято writer и request определять как w и r

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +	idStr := chi.URLParam(request, "id")
плохо читается код, не понятно какой и чей id. userID читается лучше, например

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +	accountServiceStruct usecase.AccountServiceContract
это же контракт?.. почему структ называется

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +	response := userResponse{User: user, Service: "accountservice"}
совсем мелочь, но мне кажется, что в поле сервис не обязательно еще раз уточнять, что это сервис :D

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/controller/v1/accountservice.go
> +}
ну это пока все в туду. 
прикручиваем мкуху в репо как постгрес, в нее запросы через уровень бизнес-логики usecase

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/entity/product.go
> +}
а шо тут юзер забыл?
если он напрямую с продуктом не связан, то должен быть вынесен в отдельную бизнес-сущность

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/entity/productList.go
> +}
вот здесь как раз прямую связь видно, так можно. но, по-хорошему, так делается только в случае, если они совсем только вместе используются. а если совсем огромные дтошки получатся?

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/usecase/repo/postgres.go
> +}
хорош, что нашел exec вместо query. 
может быть, стоит разбить на две разные функции чтобы логика оставалась в очевидном месте в хорошо читаемом коде, а не в запросе к бд?

2024-04-16 10:36 UTC, malinkamedok commented on accountservice/internal/usecase/repo/postgres.go
> +		"WHERE ua.id = $1;"
к коду не относится, но, наверное, для понимания происходящего нужно в ридмишку подгрузить картинку с er/dr моделями бд

2024-04-16 10:37 UTC, malinkamedok commented
в целом-то все гуд, небольшие правки по код-стайлу. 
нужно обсудить использование другого логгера и нейминг конвеншены

2024-04-16 19:06 UTC, malinkamedok approved these changes

2024-04-16 19:10 UTC, merged